name: multiagent-ml-env
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pandas
  - ipykernel
  - ipywidgets
  - pip
  - pip:
    - smolagents
    - smolagents[litellm]
    - openinference-instrumentation-smolagents
    - opentelemetry-exporter-otlp
    - opentelemetry-sdk
    - arize-phoenix
    - langchain
    - langchain-community